# Generated by Django 3.2.9 on 2021-11-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foods.food')),
            ],
        ),
    ]
