# Generated by Django 3.2.9 on 2021-11-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRecord', '0004_alter_foodrecord_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
