# Generated by Django 3.2.9 on 2021-11-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRecord', '0005_alter_foodrecord_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
