# Generated by Django 3.2.9 on 2021-11-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodRecord', '0006_alter_foodrecord_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddailyrecord',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
